# Generated by Django 5.1 on 2025-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='group_count',
            field=models.IntegerField(default=0),
        ),
    ]
