# Generated by Django 5.1 on 2025-03-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_group_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('original_text', models.TextField()),
                ('is_image', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
